include:
  - project: 'other/gitlab-ci'
    file:
      - '/templates/.nodejs-builds.yml'
      - '/templates/.docker-builds.yml'
      - '/templates/.k8s-deploys.yml'

variables:
  CI_REGISTRY_IMAGE: "${CI_REGISTRY}/yuanfu-tms/node-tms"
  CI_TAG: "$CI_COMMIT_SHORT_SHA"
  K8S_NAME_SPACE: "tms"
  K8S_DEPLOY_NAME: "node-tms"

stages:
  - build
  - docker-build
  - deploy

# 构建阶段
build:
  stage: build
  extends: .base-nodejs
  only:
    - develop

# Docker 镜像构建阶段
docker-build:
  stage: docker-build
  extends: .base-docker
  only:
    - develop

# 部署阶段
deploy:
  stage: deploy
  extends: .base-deploy
  only:
    - develop
