include:
  - project: 'other/gitlab-ci'
    file:
      - '/templates/.nodejs-builds.yml'
      - '/templates/.docker-builds.yml'
      - '/templates/.k8s-deploys.yml'

variables:
  K8S_NAME_SPACE: "yjtms"
  DOCKER_IMAGE_NAME: "node-tms"
  REGISTRY_PROJECT: "yuanfu-tms"

stages:
  - build
  - docker-build
  - deploy

# 构建阶段
build:
  stage: build
  extends: .base-nodejs

# Docker 镜像构建阶段
docker-build:
  stage: docker-build
  extends: .base-docker
  variables:
    PROJECT_NAME: $REGISTRY_PROJECT
    APP_NAME: $DOCKER_IMAGE_NAME

# 部署阶段
deploy:
  stage: deploy
  extends: .base-deploy
  variables:
    K8S_NAME_SPACE: $K8S_NAME_SPACE
    PROJECT_NAME: $REGISTRY_PROJECT
    APP_NAME: $DOCKER_IMAGE_NAME
  only:
    - develop
