.base-deploy:
  image: bitnami/kubectl:1.23.10
  script:
    - echo "Updating deployment ${K8S_DEPLOY_NAME} in namespace ${K8S_NAME_SPACE}..."
    - kubectl set image deployment/${K8S_DEPLOY_NAME} ${K8S_DEPLOY_NAME}=${CI_REGISTRY_IMAGE}:${CI_TAG} -n ${K8S_NAME_SPACE}
    - echo "Deployment ${K8S_DEPLOY_NAME} updated successfully."
    - echo "Upgraded image: ${CI_REGISTRY_IMAGE}:${CI_TAG}"
  dependencies:
    - docker-build
