.base-deploy:

  variables:
    K8S_PROJECT: "default"
    APP_NAME: "test"

  image: bitnami/kubectl:latest
  script:
    - |
      APP_IMAGE=$(cat image.txt)
      kubectl set image deployment/${APP_NAME} ${APP_NAME}=${APP_IMAGE} -n ${K8S_PROJECT}

  dependencies:
    - docker-build
