# 定义一个 Node.js 构建阶段
.base-nodejs:
  image: yaokun/node:14.19.3
  variables:
    NODE_OPTIONS: '--max-old-space-size=3072'
    KUBERNETES_CPU_REQUEST: 1800m
    KUBERNETES_CPU_LIMIT: 2500m
    KUBERNETES_MEMORY_REQUEST: 4000Mi
    KUBERNETES_MEMORY_LIMIT: 4500Mi
  before_script:
    - cnpm install
  script:
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - dist/
